package conf

const Version = "0.0.1"

const (
	CONTENT_TYPE_JSON                               = "application/json"
	CONTENT_TYPE_FORM                               = "application/x-www-form-urlencoded"
	CONTENT_TYPE_OCTET                              = "application/octet-stream"
	API_HOST                                        = "open.douyin.com"
	API_HTTP_SCHEME                                 = "https://"
	API_OAUTH_CONNECT                               = "/platform/oauth/connect/"
	API_OAUTH_ACCESS_TOKEN                          = "/oauth/access_token/"
	API_OAUTH_REFRESH_TOKEN                         = "/oauth/refresh_token/"
	API_OAUTH_RENEW_REFRESH_TOKEN                   = "/oauth/renew_refresh_token/"
	API_OAUTH_USERINFO                              = "/oauth/userinfo/"
	API_OAUTH_CLIENT_ACCESS_TOKEN                   = "/oauth/client_token/"
	API_VIDEO_LIST                                  = "/video/list/"
	API_VIDEO_UPLOAD                                = "/video/upload/"
	API_VIDEO_UPLOAD_PART_INIT                      = "/video/part/init/"
	API_VIDEO_UPLOAD_PART_UPLOAD                    = "/video/part/upload/"
	API_VIDEO_UPLOAD_PART_COMPLETE                  = "/video/part/complete/"
	API_VIDEO_CREATE                                = "/video/create/"
	API_VIDEO_DELETE                                = "/video/delete/"
	API_VIDEO_DATA                                  = "/video/data/"
	API_IMAGE_UPLOAD                                = "/image/upload/"
	API_IMAGE_CREATE                                = "/image/create/"
	API_AWEME_SHARE                                 = "/share-id/"
	API_DATA_EXTERNAL_USER_ITEM                     = "/data/external/user/item/"
	API_DATA_EXTERNAL_USER_FANS                     = "/data/external/user/fans/"
	API_DATA_EXTERNAL_USER_LIKE                     = "/data/external/user/like/"
	API_DATA_EXTERNAL_USER_COMMENT                  = "/data/external/user/comment/"
	API_DATA_EXTERNAL_USER_SHARE                    = "/data/external/user/share/"
	API_DATA_EXTERNAL_USER_PROFILE                  = "/data/external/user/profile/"
	API_DATA_EXTERNAL_ITEM_BASE                     = "/data/external/item/base/"
	API_DATA_EXTERNAL_ITEM_LIKE                     = "/data/external/item/like/"
	API_DATA_EXTERNAL_ITEM_COMMENT                  = "/data/external/item/comment/"
	API_DATA_EXTERNAL_ITEM_PLAY                     = "/data/external/item/play/"
	API_DATA_EXTERNAL_ITEM_SHARE                    = "/data/external/item/share/"
	API_HOT_SEARCH_SENTENCES                        = "/hotsearch/sentences/"
	API_HOT_SEARCH_TRENDING_SENTENCES               = "/hotsearch/trending/sentences/"
	API_HOT_SEARCH_VIDEOS                           = "/hotsearch/videos/"
	API_FANS_LIST                                   = "/fans/list/"
	API_FANS_DATA                                   = "/fans/data/"
	API_DATA_EXTERNAL_FANS_SOURCE                   = "/data/extern/fans/source/"
	API_DATA_EXTERNAL_FANS_FAVOURITE                = "/data/extern/fans/favourite/"
	API_DATA_EXTERNAL_FANS_COMMENT                  = "/data/extern/fans/comment/"
	API_FOLLOWING_LIST                              = "/following/list/"
	API_ITEM_COMMENT_LIST                           = "/item/comment/list/"
	API_ITEM_COMMENT_REPLY_LIST                     = "/item/comment/reply/list/"
	API_ITEM_COMMENT_REPLY                          = "/item/comment/reply/"
	API_EVENT_STATUS_LIST                           = "/event/status/list/"
	API_EVENT_STATUS_UPDATE                         = "/event/status/update/"
	API_STAR_HOT_LIST                               = "/star/hot_list/"
	API_STAR_AUTHOR_SCORE_V2                        = "/star/author_score_v2/"
	API_STAR_AUTHOR_SCORE                           = "/star/author_score/"
	API_JS_TICKET                                   = "/js/getticket/"
	API_DISCOVERY_ENT_RANK_ITEM                     = "/discovery/ent/rank/item/"
	API_DISCOVERY_ENT_RANK_VERSION                  = "/discovery/ent/rank/version/"
	API_DATA_EXTERNAL_BILLBOARD_GAME_CONSOLE        = "/data/extern/billboard/game/console/"        // 获取单机主机榜数据
	API_DATA_EXTERNAL_BILLBOARD_GAME_INFO           = "/data/extern/billboard/game/inf/"            // 获取游戏资讯数据
	API_DATA_EXTERNAL_BILLBOARD_DRAME_OVERALL       = "/data/extern/billboard/drama/overall/"       // 获取剧情总榜数据
	API_DATA_EXTERNAL_BILLBOARD_CAR_OVERALL         = "/data/extern/billboard/car/overall/"         // 获取汽车总榜数据
	API_DATA_EXTERNAL_BILLBOARD_CAR_COMMENT         = "/data/extern/billboard/car/comment/"         // 获取评车榜数据
	API_DATA_EXTERNAL_BILLBOARD_CAR_PLAY            = "/data/extern/billboard/car/play/"            // 获取玩车榜数据
	API_DATA_EXTERNAL_BILLBOARD_CAR_USE             = "/data/extern/billboard/car/use/"             // 获取用车榜数据
	API_DATA_EXTERNAL_BILLBOARD_CAR_DRIVER          = "/data/extern/billboard/car/driver/"          // 获取驾考榜数据
	API_DATA_EXTERNAL_BILLBOARD_AMUSEMENT_OVERALL   = "/data/extern/billboard/amusement/overall/"   // 获取搞笑总榜数据
	API_DATA_EXTERNAL_BILLBOARD_AMUSEMENT_NEW       = "/data/extern/billboard/amusement/new/"       // 获取搞笑新势力数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_OVERALL       = "/data/extern/billboard/cospa/overall/"       // 获取二次元总榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_QING_MAN      = "/data/extern/billboard/cospa/qing_man/"      // 获取轻漫榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_OUT_SHOT      = "/data/extern/billboard/cospa/out_shot/"      // 获取出境拍摄榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_PAINTING      = "/data/extern/billboard/cospa/painting/"      // 获取绘画榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_VOICE_CONTROL = "/data/extern/billboard/cospa/voice_control/" // 获取声控榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_BRAIN_CAVITY  = "/data/extern/billboard/cospa/brain_cavity/"  // 获取脑洞榜数据
	API_DATA_EXTERNAL_BILLBOARD_COSPA_NEW           = "/data/extern/billboard/cospa/new/"           // 获取二次元新势力榜数据
	API_DATA_EXTERNAL_BILLBOARD_FOOD_OVERALL        = "/data/extern/billboard/food/overall/"        // 获取美食总榜数据
	API_DATA_EXTERNAL_BILLBOARD_FOOD_NEW            = "/data/extern/billboard/food/new/"            // 获取美食新势力榜数据
	API_DATA_EXTERNAL_BILLBOARD_FOOD_TUTORIAL       = "/data/extern/billboard/food/tutorial/"       // 获取美食教程榜数据
	API_DATA_EXTERNAL_BILLBOARD_FOOD_SHOP           = "/data/extern/billboard/food/shop/"           // 获取美食探店榜数据
	API_DATA_EXTERNAL_BILLBOARD_TRAVEL_OVERALL      = "/data/extern/billboard/travel/overall/"      // 获取旅游总榜数据
	API_DATA_EXTERNAL_BILLBOARD_TRAVEL_NEW          = "/data/extern/billboard/travel/new/"          // 获取旅游新势力榜数据
	API_DATA_EXTERNAL_BILLBOARD_STARS               = "/data/extern/billboard/stars/"               // 获取娱乐明星榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_OVERALL       = "/data/extern/billboard/sport/overall/"       // 获取体育总榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_BASKETBALL    = "/data/extern/billboard/sport/basketball/"    // 获取篮球榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_SOCCER        = "/data/extern/billboard/sport/soccer/"        // 获取足球榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_COMPREHENSIVE = "/data/extern/billboard/sport/comprehensive/" // 获取综合体育榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_FITNESS       = "/data/extern/billboard/sport/fitness/"       // 获取运动健身榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_OUTDOORS      = "/data/extern/billboard/sport/outdoors/"      // 获取户外运动榜数据
	API_DATA_EXTERNAL_BILLBOARD_SPORT_TABLE_TENNIES = "/data/extern/billboard/sport/table_tennis/"  // 获取台球榜数据(非网球数据)
	API_DATA_EXTERNAL_BILLBOARD_SPORT_CULTURE       = "/data/extern/billboard/sport/culture/"       // 获取运动文化榜数据
	API_DATA_EXTERNAL_BILLBOARD_TOPIC               = "/data/extern/billboard/topic/"               // 获取话题榜数据
	API_DATA_EXTERNAL_BILLBOARD_PROP                = "/data/extern/billboard/prop/"                // 获取话题榜数据
	API_DATA_EXTERNAL_BILLBOARD_HOT_VIDEO           = "/data/extern/billboard/hot_video/"           // 获取热门视频数据
	API_DATA_EXTERNAL_BILLBOARD_LIVE                = "/data/extern/billboard/live/"                // 获取直播榜数据
	API_DATA_EXTERNAL_BILLBOARD_MUSIC_HOT           = "/data/extern/billboard/music/hot/"           // 获取音乐热歌榜数据
	API_DATA_EXTERNAL_BILLBOARD_MUSIC_SOAR          = "/data/extern/billboard/music/soar/"          // 获取音乐飙升榜数据
	API_DATA_EXTERNAL_BILLBOARD_MUSIC_ORIGINAL      = "/data/extern/billboard/music/original/"      // 获取音乐原创榜数据
)
